# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fish_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, verbose_name='コメント')),
                ('latitude', models.FloatField(verbose_name='緯度')),
                ('longitude', models.FloatField(verbose_name='経度')),
                ('create_time', models.DateField(auto_now=True, verbose_name='登録時間')),
                ('image', models.ImageField(upload_to='images/', verbose_name='画像')),
                ('user', models.CharField(max_length=200, verbose_name='登録者')),
            ],
        ),
        migrations.CreateModel(
            name='gimmic_master',
            fields=[
                ('gimmic_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='仕掛けID')),
            ],
        ),
        migrations.CreateModel(
            name='line_master',
            fields=[
                ('line_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='商品ID')),
                ('type_size', models.FloatField(verbose_name='号数')),
            ],
        ),
        migrations.CreateModel(
            name='maker_master',
            fields=[
                ('maker_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='メーカーID')),
                ('maker_name', models.CharField(max_length=200, verbose_name='名称')),
            ],
        ),
        migrations.CreateModel(
            name='ownership_master',
            fields=[
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='ユーザID')),
            ],
        ),
        migrations.CreateModel(
            name='product_master',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='商品ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='名称')),
                ('create_date', models.DateField(auto_now=True, verbose_name='登録日')),
                ('image', models.ImageField(upload_to='images/', verbose_name='画像')),
                ('classification', models.IntegerField(verbose_name='区分')),
                ('maker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FishResult.maker_master', verbose_name='メーカーID')),
            ],
        ),
        migrations.CreateModel(
            name='reel_master',
            fields=[
                ('reel_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='商品ID')),
                ('wind_length', models.FloatField(verbose_name='巻き取り長さ')),
                ('weight', models.FloatField(verbose_name='重さ')),
            ],
        ),
        migrations.CreateModel(
            name='rod_master',
            fields=[
                ('rod_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='商品ID')),
                ('length', models.IntegerField(verbose_name='長さ')),
            ],
        ),
        migrations.CreateModel(
            name='rure_master',
            fields=[
                ('rure_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='商品ID')),
                ('weight', models.IntegerField(verbose_name='重さ')),
            ],
        ),
        migrations.CreateModel(
            name='set_master',
            fields=[
                ('set_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='セットID')),
                ('set_name', models.CharField(max_length=200, verbose_name='名称')),
                ('create_date', models.DateField(auto_now=True, verbose_name='登録日')),
                ('image', models.ImageField(upload_to='images/', verbose_name='画像')),
                ('user', models.CharField(max_length=200, verbose_name='登録者')),
                ('gimmic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FishResult.gimmic_master', verbose_name='仕掛けID')),
                ('line_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FishResult.line_master', verbose_name='ラインID')),
                ('reel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FishResult.reel_master', verbose_name='リールID')),
                ('rod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FishResult.rod_master', verbose_name='ロッドID')),
                ('rure_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FishResult.rure_master', verbose_name='ルアーID')),
            ],
        ),
        migrations.CreateModel(
            name='use_master',
            fields=[
                ('use_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='用途ID')),
                ('use_name', models.CharField(max_length=200, verbose_name='名称')),
                ('remarks', models.CharField(max_length=200, verbose_name='備考')),
            ],
        ),
        migrations.CreateModel(
            name='user_master',
            fields=[
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='ユーザID')),
                ('user_name', models.CharField(max_length=200, verbose_name='ユーザ名')),
            ],
        ),
        migrations.CreateModel(
            name='val_info_master',
            fields=[
                ('val_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('classification', models.IntegerField(verbose_name='区分')),
                ('val_info_if', models.IntegerField(verbose_name='構成ID')),
                ('input_type', models.CharField(max_length=200, verbose_name='inputタイプ')),
                ('input_name', models.CharField(max_length=200, verbose_name='input名称')),
                ('dataset', models.CharField(max_length=200, verbose_name='dataset')),
            ],
        ),
        migrations.CreateModel(
            name='worm_master',
            fields=[
                ('worm_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='商品ID')),
                ('inchi', models.IntegerField(verbose_name='長さ')),
            ],
        ),
        migrations.AddField(
            model_name='set_master',
            name='worm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FishResult.worm_master', verbose_name='ワームID'),
        ),
        migrations.AddField(
            model_name='product_master',
            name='use_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FishResult.use_master', verbose_name='用途ID'),
        ),
        migrations.AddField(
            model_name='product_master',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FishResult.user_master', verbose_name='ユーザID'),
        ),
        migrations.AddField(
            model_name='ownership_master',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FishResult.product_master', verbose_name='商品ID'),
        ),
        migrations.AddField(
            model_name='fish_result',
            name='set_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FishResult.set_master', verbose_name='セットID'),
        ),
    ]
