# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FishResult', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maker_master',
            name='maker_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='メーカーID'),
        ),
        migrations.AlterField(
            model_name='product_master',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='商品ID'),
        ),
        migrations.AlterField(
            model_name='set_master',
            name='set_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='セットID'),
        ),
        migrations.AlterField(
            model_name='use_master',
            name='use_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='用途ID'),
        ),
    ]
