# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FishResult', '0002_auto_20160809_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='gimmic_master',
            name='gimmic_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='line_master',
            name='line_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='reel_master',
            name='reel_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='rod_master',
            name='rod_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='rure_master',
            name='rure_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='worm_master',
            name='worm_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='fish_result',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='product_master',
            name='classification',
            field=models.CharField(choices=[('1', 'ロッド'), ('2', 'リール'), ('3', 'ライン'), ('4', 'ルアー'), ('5', 'ワーム'), ('6', '仕掛け')], max_length=2, verbose_name='区分'),
        ),
        migrations.AlterField(
            model_name='product_master',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='set_master',
            name='gimmic_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='FishResult.gimmic_master', verbose_name='仕掛けID'),
        ),
        migrations.AlterField(
            model_name='set_master',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='set_master',
            name='rure_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='FishResult.rure_master', verbose_name='ルアーID'),
        ),
        migrations.AlterField(
            model_name='set_master',
            name='worm_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='FishResult.worm_master', verbose_name='ワームID'),
        ),
    ]
