# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FishResult', '0003_auto_20160813_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gimmic_master',
            name='gimmic_name',
        ),
        migrations.RemoveField(
            model_name='line_master',
            name='line_name',
        ),
        migrations.RemoveField(
            model_name='reel_master',
            name='reel_name',
        ),
        migrations.RemoveField(
            model_name='rod_master',
            name='rod_name',
        ),
        migrations.RemoveField(
            model_name='rure_master',
            name='rure_name',
        ),
        migrations.RemoveField(
            model_name='worm_master',
            name='worm_name',
        ),
    ]
