# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FishResult', '0005_auto_20160816_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_master',
            name='maker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FishResult.maker_master', verbose_name='メーカーID'),
        ),
        migrations.AlterField(
            model_name='reel_master',
            name='weight',
            field=models.FloatField(verbose_name='重さ(グラム)'),
        ),
        migrations.AlterField(
            model_name='reel_master',
            name='wind_length',
            field=models.FloatField(verbose_name='巻き取り長さ(m)'),
        ),
        migrations.AlterField(
            model_name='rod_master',
            name='length',
            field=models.IntegerField(verbose_name='長さ(m)'),
        ),
    ]
