# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FishResult', '0007_auto_20160817_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gimmic_master',
            name='gimmic_name',
            field=models.CharField(max_length=200, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='line_master',
            name='line_name',
            field=models.CharField(max_length=200, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='reel_master',
            name='reel_name',
            field=models.CharField(max_length=200, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='rod_master',
            name='rod_name',
            field=models.CharField(max_length=200, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='rure_master',
            name='rure_name',
            field=models.CharField(max_length=200, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='worm_master',
            name='worm_name',
            field=models.CharField(max_length=200, verbose_name='商品名'),
        ),
    ]
