# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FishResult', '0008_auto_20160817_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish_result',
            name='comment',
            field=models.CharField(blank='True', max_length=200, verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='worm_master',
            name='inchi',
            field=models.IntegerField(verbose_name='長さ(インチ)'),
        ),
    ]
