# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FishResult', '0009_auto_20160818_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish_result',
            name='set_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FishResult.set_master', verbose_name='セット'),
        ),
        migrations.AlterField(
            model_name='fish_result',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FishResult.user_master', verbose_name='登録者'),
        ),
    ]
