# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-29 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FishResult', '0012_auto_20160829_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='use_master',
            name='use_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='用途ID'),
        ),
    ]
